### ISSUE TITLE
The requested platform 'TuyaPlatform' was not registered by any plugin.

### ISSUE THREAD

**Issue by walshy1009** [iRayanKhan/homebridge-tuya#113]
**Checklist**
- [X] I have read the common issues wiki page
- [X] I have checked to make sure the plugin is up to date

**Describe the bug**
Requested platform 'TuyaPlatform' was not requested by any plugin despite installing this plugin via sudo npm install -g git+https://github.com/spadival/homebridge-tuya.git

**To Reproduce**

**Expected behavior**
Expected to work based off instructions I followed

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
-  iOS version: 14.0 Beta 2
-  Homehubs: homebridge 
 - Node Version: v12.18.2
 - Plugin Version: v1.1.1
-  Accessory Type: Kogan Garage Door Opener

**Additional context**
Log upon start up:

[7/17/2020, 3:35:31 PM] [HB Supervisor] Restarting Homebridge...
[7/17/2020, 3:35:31 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/17/2020, 3:35:31 PM] [HB Supervisor] Started Homebridge v1.1.1 with PID: 24954
[7/17/2020, 3:35:31 PM] Loaded config.json with 1 accessories and 4 platforms.
[7/17/2020, 3:35:31 PM] ---
[7/17/2020, 3:35:32 PM] Loaded plugin: homebridge-config-ui-x@4.23.2
[7/17/2020, 3:35:32 PM] Registering platform 'homebridge-config-ui-x.config'
[7/17/2020, 3:35:32 PM] ---
[7/17/2020, 3:35:32 PM] Loaded plugin: homebridge-panasonic-viera-tv@7.2.0
[7/17/2020, 3:35:32 PM] Plugin 'homebridge-panasonic-viera-tv' tried to register with an incorrect plugin identifier: 'homebridge-panasonic'. Please report this to the developer!
[7/17/2020, 3:35:32 PM] Registering accessory 'homebridge-panasonic-viera-tv.Panasonic-TV'
[7/17/2020, 3:35:32 PM] ---
[7/17/2020, 3:35:32 PM] Loaded plugin: homebridge-ring@9.6.0
[7/17/2020, 3:35:32 PM] Registering platform 'homebridge-ring.Ring'
[7/17/2020, 3:35:32 PM] ---
[7/17/2020, 3:35:32 PM] Loaded plugin: homebridge-tuya@1.0.2
[7/17/2020, 3:35:32 PM] Registering platform 'homebridge-tuya.TuyaLan'
[7/17/2020, 3:35:32 PM] ---
[7/17/2020, 3:35:32 PM] Loaded plugin: homebridge-yeelighter@1.5.12
[7/17/2020, 3:35:32 PM] Registering platform 'homebridge-yeelighter.Yeelighter'
[7/17/2020, 3:35:32 PM] ---
[7/17/2020, 3:35:32 PM] Loading 4 platforms...
[7/17/2020, 3:35:32 PM] [Config] Initializing config platform...
[7/17/2020, 3:35:32 PM] [Config] Running in Service Mode
[7/17/2020, 3:35:32 PM] [Yeelighter] Initializing Yeelighter platform...
[7/17/2020, 3:35:32 PM] [Ring] Initializing Ring platform...
[7/17/2020, 3:35:32 PM] Error loading platform requested in your config.json at position 4
[7/17/2020, 3:35:32 PM] Error: The requested platform 'TuyaPlatform' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/17/2020, 3:35:32 PM] Got SIGTERM, shutting down Homebridge...
[7/17/2020, 3:35:37 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

config.json setup:
{
    "bridge": {
        "name": "Homebridge 2431",
        "username": "0E:13:DC:D5:24:31",
        "port": 51781,
        "pin": "728-08-596"
    },
    "accessories": [
        {
            "accessory": "Panasonic-TV",
            "name": "Front Room TV",
            "ipaddress": "192.168.0.20",
            "model": "YOUR_TV_MODEL_HERE_(OPTIONAL)",
            "serialNumber": "YOUR_TV_SERIAL_NUMBER_HERE_(OPTIONAL)",
            "inputs": [
                {
                    "id": "TV",
                    "name": "TV",
                    "type": "TV"
                },
                {
                    "id": "HDMI 3",
                    "name": "Chromecast",
                    "type": "HDMI"
                },
                {
                    "id": "Netflix",
                    "name": "Netflix",
                    "type": "APPLICATION",
                    "appID": "0010000200000001"
                },
                {
                    "id": "YouTube",
                    "name": "YouTube",
                    "type": "APPLICATION",
                    "appID": "0070000200170001"
                }
            ]
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": false,
            "override": [
                {
                    "useNameAsId": false
                }
            ],
            "platform": "Yeelighter"
        },
        {
            "refreshToken": "censored",
            "platform": "Ring"
        },
        {
            "platform": "TuyaPlatform",
            "name": "TuyaPlatform",
            "devices": [
                {
                    "name": "Garage Door",
                    "type": "GarageDoor",
                    "manufacturer": "Test",
                    "model": "Testing01",
                    "id": "censored",
                    "key": "censored"
                }
            ]
        }
    ]
}

**Comment by walshy1009** [comment]
Fixed my own problem! Had to change the "platform" name from TuyaPlatform to TuyaLan
