### ISSUE TITLE
Trouble retrieving Tuya ID Keys 

### ISSUE THREAD

**Issue by arubarb** [iRayanKhan/homebridge-tuya#126]
Hi all just trying to retrieve my Tuya ID Keys from the IoT platform to put into the plugin however I can't seem to retrieve it from the QR code method or the Command line Interface method mentioned in this video https://www.youtube.com/watch?v=oq0JL_wicKg I've followed them both a couple of times, the account is linked up and have devices showing and each time has the same result.. (xxxxx is personal info)

**Trying the QR Code Method**

sudo tuya-cli wizard
? The API key from tuya.com: XXXXX
? The API secret from tuya.com XXXXX
? Provide a 'virtual ID' of a device currently registered in the app: XXXX
There was an issue fetching that device. Make sure your account is linked and the ID is correct.here was an issue fetching that device. Make sure your account is linked and the ID is correct.

**Trying the Command line method**

tuya-cli link --api-key xxxxx --api-secret xxxxx --schema xxxxx --ssid xxxxx --password xxxxx --region eu
✖ Device(s) failed to be registered!
Error: you don't have access to this API
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Anyone have any idea why Tuya doesn't seem to want to let me produce these ID keys?

**Comment by arubarb** [comment]
I fixed this by adjusting settings in Tuya API settings. I opened Authorisation Management, Device Management & Device Control.
