### ISSUE TITLE
Dehumidifer

### ISSUE THREAD

**Issue by jahnkenneth** [iRayanKhan/homebridge-tuya#159]
Have added a dehumidifier, and I can see it on the Home app.
However I experience the following problems:
- When turning off the dehumidifier via the Tuya app, Homebridge crashes (it says in the log i got a sigterm"
- Changing target humidity in the Home app does nothing, the target humidity of the device does not change
- The Home app does not get the humidity reading from the device

**Comment by jahnkenneth** [comment]
Error in the log when turning the dehumidifier off via the Tuya app:
ReferenceError: characteristicRotationSpeed is not defined
    at TuyaAccessory.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tuya/lib/DehumidifierAccessory.js:134:25)
    at TuyaAccessory.emit (events.js:314:20)
    at TuyaAccessory._change (/home/hoobs/.hoobs/node_modules/homebridge-tuya/lib/TuyaAccessory.js:392:18)
    at TuyaAccessory._msgHandler_3_3 (/home/hoobs/.hoobs/node_modules/homebridge-tuya/lib/TuyaAccessory.js:318:30)
    at /home/hoobs/.hoobs/node_modules/async/dist/async.js:3201:13
    at Object.process (/home/hoobs/.hoobs/node_modules/async/dist/async.js:1427:21)
    at /home/hoobs/.hoobs/node_modules/async/dist/async.js:1285:23
    at Immediate.<anonymous> (/home/hoobs/.hoobs/node_modules/async/dist/async.js:73:45)
    at processImmediate (internal/timers.js:461:21)

**Comment by iRayanKhan** [comment]
Your device may not have that characteristic, can you please update to the latest version of the plugin and see if you still run into this issue? If so, please re-open this issue.
