### ISSUE TITLE
Cannot control white/colour bulb

### ISSUE THREAD

**Issue by hosigi05** [iRayanKhan/homebridge-tuya#303]
**Checklist**
- [x] I have read the common issues wiki page 
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
* When adding a colour bulb
* Then I get a characteristics error

**To Reproduce**
Debug error:

`[6/27/2021, 7:21:02 PM] [TuyaLan] Discovered Abzug (bf5dd637872bbc1267dpr9) identified as RGBTWLight (3.3)
[Tuya] Changing ping gap for Abzug to 9s
[Tuya DEBUG] reconnect called for Abzug
[Tuya] Discovery ended.

[6/27/2021, 7:21:02 PM] [TuyaLan] Connected to Abzug
[Tuya] Sending first query to Abzug (3.3)
[Tuya] Heard back from Abzug with command 10

[6/27/2021, 7:21:02 PM] [TuyaLan] Ready to handle Abzug (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":0,"24":"001a02640259","25":"000e0d0000000000000000c80000","26":0,"101":true}
[Tuya] Color format for Abzug (3.3) is undetectable.

[6/27/2021, 7:21:02 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

[6/27/2021, 7:21:02 PM] [homebridge-tuya] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1915:14)
    at On.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at RGBTWLightAccessory._registerCharacteristics (/homebridge/node_modules/homebridge-tuya/lib/RGBTWLightAccessory.js:50:14)
    at TuyaAccessory.<anonymous> (/homebridge/node_modules/homebridge-tuya/lib/BaseAccessory.js:22:18)
    at Object.onceWrapper (events.js:483:26)
    at TuyaAccessory.emit (events.js:376:20)
    at TuyaAccessory._change (/homebridge/node_modules/homebridge-tuya/lib/TuyaAccessory.js:407:18)
    at TuyaAccessory._msgHandler_3_3 (/homebridge/node_modules/homebridge-tuya/lib/TuyaAccessory.js:333:30)
    at /homebridge/node_modules/homebridge-tuya/node_modules/async/dist/async.js:3201:13`

**Expected behavior**
I should be able to switch the light on and off

**Screenshots**
![IMG_3150](https://user-images.githubusercontent.com/86551275/123539028-fb0c6a00-d737-11eb-92ab-d3dcd40cf7b6.jpg)

**Environment (please complete the following information):**
 - Plugin Version: homebridge-tuya v2.0.1
-  Accessory Type: Tuya White/Colour bulb

**Additional context**
Tuya device Id: bf5dd637872bbc1267dpr9

THANKS A LOT FOR THE HELP!

**Comment by hmenzagh** [comment]
Same error message here, 

```
characteristic value expected boolean and received undefined
```

**Comment by tooh** [comment]
same error message here

**Comment by dansleboby** [comment]
Set this settings:

dbPower: 20
dpMode: 21
dpBrightness: 22
dpColorTemperature: 23
dpColor: 24
colorFunction: hsb

**Comment by hosigi05** [comment]
> Set this settings:
> 
> dbPower: 20 dpMode: 21 dpBrightness: 22 dpColorTemperature: 23 dpColor: 24 colorFunction: hsb

This solved the problem. Thanks a lot!
