### ISSUE TITLE
Slow updating 

### ISSUE THREAD

**Issue by jamesscf** [iRayanKhan/homebridge-tuya#41]
When I enter the home app, the status goes from (on/off) to updating which takes about 20 seconds to come back to their actual status. Hey Siri seems to work fine immediately but not physically in the home app. This has only happened since yesterday. Thanks

**Comment by codetheweb** [comment]
Hmm, sounds like it might be more of a network issue.

Can you post the output of `DEBUG=* homebridge` when the problem occurs?

**Comment by jamesscf** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::43007
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by codetheweb** [comment]
As TuyAPI doesn't use that port, it seems more likely that something's wrong with your Homebridge configuration.  Do you always get that error when starting Homebridge?  

Can you please post your `config.json` (feel free to obscure IDs and keys)?

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
