### ISSUE TITLE
Cannot setup 2 gang wall light switch version 3.3

### ISSUE THREAD

**Issue by rfg88** [iRayanKhan/homebridge-tuya#58]
I'm setting up a 2 gang wall light switch.  Anyone knows how to fix this error?  I getting successful connection if I just add 1 switch, but getting errors adding both.

config.json:
"platform":"TuyaPlatform",
         "name":"TuyaPlatform",
         "devices":[
            {
                "name":"Tuya Switch 1.1",
                "id":"aaaaa",
                "key":"bbbbb",
                "ip":"192.168.0.xxx",
                "version":3.3,
                "options": {
                   "dps": 1
                }
            },
            {
               "name":"Tuya Switch 1.2",
               "id":"aaaaa",
               "key":"bbbbb",
               "ip":"192.168.0.xxx",
               "version":3.3,
               "options": {
                   "dps": 2
                }
       }

Here is the error:

  TuyAPI Error event from socket. 192.168.0.xxx { Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:71:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +36ms
[9/18/2019, 3:51:19 PM] [TuyaPlatform] ERROR: not responding Tuya Switch 1.2 Error: Error from socket
    at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
    at Socket.emit (events.js:193:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:621:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:72:12)
  TuyAPI Socket closed: 192.168.0.xxx +111ms

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
