### ISSUE TITLE
EPIPE Error when trying to get device key for Tuya lights

### ISSUE THREAD

**Issue by sanspoint** [iRayanKhan/homebridge-tuya#85]
`Intercepted certificate request
Error: EPIPE Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:695:22)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
`

Help?

**Comment by sanspoint** [comment]
This issue has occurred with multiple iOS apps, and on multiple ports.

**Comment by shanelilley** [comment]
> This issue has occurred with multiple iOS apps, and on multiple ports.

I get the same. None of these solutions work for me at all. Just about at wits end.

**Comment by iRayanKhan** [comment]
Closing: Please use the Tuya cli wizard.
